# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='item.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nitem.proto\" \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\x05Items\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"\r\n\x0bNullRequest\"\"\n\x0fSuccessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\rFoundResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x32\x83\x02\n\x08Itemizer\x12%\n\nCreateItem\x12\x05.Item\x1a\x10.SuccessResponse\x12\'\n\x0b\x43reateItems\x12\x06.Items\x1a\x10.SuccessResponse\x12 \n\x08GetItems\x12\x0c.NullRequest\x1a\x06.Items\x12.\n\x11\x43reateItemsStream\x12\x05.Item\x1a\x10.SuccessResponse(\x01\x12\'\n\x0eGetItemsStream\x12\x0c.NullRequest\x1a\x05.Item0\x01\x12,\n\x0f\x46indItemsStream\x12\x05.Item\x1a\x0e.FoundResponse(\x01\x30\x01\x62\x06proto3'
)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Item.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Item.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=46,
)


_ITEMS = _descriptor.Descriptor(
  name='Items',
  full_name='Items',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='Items.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=77,
)


_NULLREQUEST = _descriptor.Descriptor(
  name='NullRequest',
  full_name='NullRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=92,
)


_SUCCESSRESPONSE = _descriptor.Descriptor(
  name='SuccessResponse',
  full_name='SuccessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='SuccessResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=128,
)


_FOUNDRESPONSE = _descriptor.Descriptor(
  name='FoundResponse',
  full_name='FoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='found', full_name='FoundResponse.found', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=160,
)

_ITEMS.fields_by_name['items'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Items'] = _ITEMS
DESCRIPTOR.message_types_by_name['NullRequest'] = _NULLREQUEST
DESCRIPTOR.message_types_by_name['SuccessResponse'] = _SUCCESSRESPONSE
DESCRIPTOR.message_types_by_name['FoundResponse'] = _FOUNDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)

Items = _reflection.GeneratedProtocolMessageType('Items', (_message.Message,), {
  'DESCRIPTOR' : _ITEMS,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:Items)
  })
_sym_db.RegisterMessage(Items)

NullRequest = _reflection.GeneratedProtocolMessageType('NullRequest', (_message.Message,), {
  'DESCRIPTOR' : _NULLREQUEST,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:NullRequest)
  })
_sym_db.RegisterMessage(NullRequest)

SuccessResponse = _reflection.GeneratedProtocolMessageType('SuccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSRESPONSE,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:SuccessResponse)
  })
_sym_db.RegisterMessage(SuccessResponse)

FoundResponse = _reflection.GeneratedProtocolMessageType('FoundResponse', (_message.Message,), {
  'DESCRIPTOR' : _FOUNDRESPONSE,
  '__module__' : 'item_pb2'
  # @@protoc_insertion_point(class_scope:FoundResponse)
  })
_sym_db.RegisterMessage(FoundResponse)



_ITEMIZER = _descriptor.ServiceDescriptor(
  name='Itemizer',
  full_name='Itemizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=422,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateItem',
    full_name='Itemizer.CreateItem',
    index=0,
    containing_service=None,
    input_type=_ITEM,
    output_type=_SUCCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateItems',
    full_name='Itemizer.CreateItems',
    index=1,
    containing_service=None,
    input_type=_ITEMS,
    output_type=_SUCCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetItems',
    full_name='Itemizer.GetItems',
    index=2,
    containing_service=None,
    input_type=_NULLREQUEST,
    output_type=_ITEMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateItemsStream',
    full_name='Itemizer.CreateItemsStream',
    index=3,
    containing_service=None,
    input_type=_ITEM,
    output_type=_SUCCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetItemsStream',
    full_name='Itemizer.GetItemsStream',
    index=4,
    containing_service=None,
    input_type=_NULLREQUEST,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindItemsStream',
    full_name='Itemizer.FindItemsStream',
    index=5,
    containing_service=None,
    input_type=_ITEM,
    output_type=_FOUNDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMIZER)

DESCRIPTOR.services_by_name['Itemizer'] = _ITEMIZER

# @@protoc_insertion_point(module_scope)
